source "https://rubygems.org"

gem "autoprefixer-rails"
gem "html-proofer"
gem "jekyll"
gem "jekyll-assets", ">= 2.3.0"
gem "jekyll-paginate"
gem "jekyll-sitemap"
gem "jemoji"
gem "mini_magick"
gem "sass"
gem "uglifier"
