source "https://rubygems.org"

gem "autoprefixer-rails"
gem "html-proofer", ">= 3.15.0"
gem "jekyll"
gem "jekyll-assets"
gem "jekyll-paginate"
gem "jekyll-sitemap"
gem "jemoji"
gem "mini_magick"
gem "sass"
gem "uglifier"
