source "https://rubygems.org"

gem "autoprefixer-rails"
gem "html-proofer", ">= 3.12.0"
gem "jekyll"
gem "jekyll-assets", ">= 2.3.0"
gem "jekyll-paginate"
gem "jekyll-sitemap"
gem "jemoji", ">= 0.10.0"
gem "mini_magick"
gem "sass"
gem "uglifier"
